//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekTweet.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeekTweet.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;created_at&quot;: &quot;Sat Nov 23 20:31:53 +0000 2013&quot;,
        ///    &quot;id&quot;: 404346588094414848,
        ///    &quot;id_str&quot;: &quot;404346588094414848&quot;,
        ///    &quot;text&quot;: &quot;Fast http://t.co/KoMRKooOzr Web Sites - nice practical book on perf optimizing http://t.co/KoMRKooOzr apps: http://t.co/9ZuuYBznNC&quot;,
        ///    &quot;source&quot;: &quot;web&quot;,
        ///    &quot;truncated&quot;: false,
        ///    &quot;in_reply_to_status_id&quot;: null,
        ///    &quot;in_reply_to_status_id_str&quot;: null,
        ///    &quot;in_reply_to_user_id&quot;: null,
        ///    &quot;in_reply_to_user_id_str&quot;: null,
        ///    &quot;in_reply_to_screen_name&quot;: null,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScottGuTimeline {
            get {
                return ResourceManager.GetString("ScottGuTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;id&quot;: 41754227,
        ///    &quot;id_str&quot;: &quot;41754227&quot;,
        ///    &quot;name&quot;: &quot;Scott Guthrie&quot;,
        ///    &quot;screen_name&quot;: &quot;scottgu&quot;,
        ///    &quot;location&quot;: &quot;Redmond, WA&quot;,
        ///    &quot;description&quot;: &quot;I live in Seattle and build a few products for Microsoft&quot;,
        ///    &quot;url&quot;: &quot;http://t.co/rkquDCVhAW&quot;,
        ///    &quot;entities&quot;: {
        ///      &quot;url&quot;: {
        ///        &quot;urls&quot;: [
        ///          {
        ///            &quot;url&quot;: &quot;http://t.co/rkquDCVhAW&quot;,
        ///            &quot;expanded_url&quot;: &quot;http://weblogs.asp.net/scottgu&quot;,
        ///            &quot;display_url&quot;: &quot;weblogs.asp.net/scottgu&quot;,
        ///            &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScottGuUser {
            get {
                return ResourceManager.GetString("ScottGuUser", resourceCulture);
            }
        }
    }
}
