//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekTweet.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GeekTweetEntities : DbContext
    {
        public GeekTweetEntities()
            : base("name=GeekTweetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Tweet> Tweets { get; set; }
    
        public virtual ObjectResult<string> FindDistinctScreenNames(string pattern)
        {
            var patternParameter = pattern != null ?
                new ObjectParameter("Pattern", pattern) :
                new ObjectParameter("Pattern", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("FindDistinctScreenNames", patternParameter);
        }
    }
}
